### ISSUE TITLE
Can we use it in TeamCity

### ISSUE THREAD

**Issue by prabhakarreddy1234** [PaulTrampert/dotnet-version#4]
I am trying to configure TeamCity as my nuget server and also CI. I am using `dotnet pack` command to pack a project a nuget and drop it to nuget server.  It 's working fine but always the version number is same. 

I tried to use `dotnet version 1.0.1` as a command in the TeamCity build step but couldn't get it to work . 

Is there anyway we can make this tool work in TeamCity and other CI Tools ?

**Comment by PaulTrampert** [comment]
I'm not terribly familiar with TeamCity (I use Jenkins usually), but you'll need to make sure the working directory is the same as the project.json you're trying to version. So, for example, most dotnet core solutions have a structure like this:

```
sln/global.json
    -src
        -project1
            -project.json
        -project2
            -project.json
    -test
        -testproject
            -project.json
```

If you want to set the version of project1, you have to do the following (assuming you're using it from the tools section of your project.json)

```
cd src\project1
dotnet version 1.0.1
```

Attempting to call `dotnet version` from the solution directory won't work because the cli won't find a project.json listing the dotnet-version tool.

If you're trying to use this tool by installing it on the system PATH, it's not going to work. I haven't implemented it in such a way as to take the project.json file as a command line argument. I could do that, but right now I don't want to invest a whole lot of time in this tool until they clear up how assembly versioning is going to work in dotnet core once they switch back to using msbuild/csproj.

**Comment by PaulTrampert** [comment]
Closing for lack of feedback from OP.
